language: generic 

services:
  - docker

after_success:
  - docker build -t icarus2io/icarus-cloud-redis .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push icarus2io/icarus-cloud-redis

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'icarus-redis'
  env: 'Icarusredis-env'
  bucket_name: 'elasticbeanstalk-us-west-1-473472325949'
  bucket_path: 'icarus-redis'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY